# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./flexera.automation.selenium
      run: dotnet restore
    - name: Build
      working-directory: ./flexera.automation.selenium
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./flexera.automation.selenium
      run: dotnet test --no-build --verbosity normal --logger html 
    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/flexera.automation.selenium/TestResults/TestResults_*.html'
    
